Algoritmo "aula7"


Var
nome :caractere
produtos : vetor [1..4] de caractere
numeros: vetor [1..3] de inteiro
i : inteiro
Inicio
nome <- "Victor"
nome <- "Pedro"
produtos [1] <- "Banana"
produtos [2] <- "Salgadinho"
produtos [3] <- "Refrigerante"
produtos [4] <- "Café"


//enquanto (condicao)
//contador <- contador +1
para i <- 1 ate 3 faca
     leia (numeros[i])
fimPara
para i <- 1 ate 3 faca
     escreval("n",i,"º",numeros [i])
Fimpara
Fimalgoritmo